# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(related_name='items', to='item.Item'),
        ),
    ]
